/*
 * OriginStamp Documentation
 * <br/>The following documentation describes the API v3 for OriginStamp. With this documentation you are able to try out the different requests and see the responses. For the authorization, add your API key to the Authorization header of your request.<br/><h2>Invoice</h2><p>The invoice is based on your individual usage. The following table illustrates the request types, that are billed in credits.</p><table><tr><th>Request Type</th><th>Condition</th><th>Credits</th><tr><td style='border-bottom-style:solid; border-color: #c0c0c0;'></td><tr><th>Submission</th><th>create timestamp</th><th>1 Credit</th><tr><th>Submission</th><th>timestamp already exists</th><th>0.3 Credits</th><tr><th>Status</th><th>no timestamp information available</th><th>0.1 Credit</th><tr><th>Status</th><th>timestamp information</th><th>0.3 Credits</th><tr><th>Proof</th><th>no proof available</th><th>0.1 Credits</th><tr><th>Proof</th><th>merkle tree as proof</th><th>3 Credits</th><tr><th>Proof</th><th>seed as proof</th><th>3 Credits</th><tr><th>Proof</th><th>PDF Certificate</th><th>5 Credits</th><tr><th>Notification</th><th>webhook notification</th><th>1.5 Credits</th><tr><th>Notification</th><th>mail notification</th><th>5 Credits</th><tr><th>Notification</th><th>trigger webhook</th><th>5 0.3</th></table>
 *
 * OpenAPI spec version: 3.0
 * Contact: mail@originstamp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.originstamp.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.originstamp.model.SchedulerResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The default service response object uses error code and message to indicate errors. These errors are handled by the client.
 */
@ApiModel(description = "The default service response object uses error code and message to indicate errors. These errors are handled by the client.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-29T13:43:50.106+01:00")
public class DefaultSchedulerResponse {
  @SerializedName("data")
  private SchedulerResponse data = null;

  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("error_message")
  private String errorMessage = null;

  public DefaultSchedulerResponse data(SchedulerResponse data) {
    this.data = data;
    return this;
  }

   /**
   * generic response object, which contains the response data, e.g. timestamp information
   * @return data
  **/
  @ApiModelProperty(required = true, value = "generic response object, which contains the response data, e.g. timestamp information")
  public SchedulerResponse getData() {
    return data;
  }

  public void setData(SchedulerResponse data) {
    this.data = data;
  }

  public DefaultSchedulerResponse errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * contains the error of the request. if the error code is 0, everything is fine.
   * @return errorCode
  **/
  @ApiModelProperty(required = true, value = "contains the error of the request. if the error code is 0, everything is fine.")
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DefaultSchedulerResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * contains the error message, that occurred. If it is empty, everything is fine
   * @return errorMessage
  **/
  @ApiModelProperty(required = true, value = "contains the error message, that occurred. If it is empty, everything is fine")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DefaultSchedulerResponse defaultSchedulerResponse = (DefaultSchedulerResponse) o;
    return Objects.equals(this.data, defaultSchedulerResponse.data) &&
        Objects.equals(this.errorCode, defaultSchedulerResponse.errorCode) &&
        Objects.equals(this.errorMessage, defaultSchedulerResponse.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errorCode, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DefaultSchedulerResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

