/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


package com.originstamp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DTO for the download link of a proof request.
 */
@ApiModel(description = "DTO for the download link of a proof request.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-18T14:06:09.411+01:00")
public class DownloadLinkResponse {
  @SerializedName("download_url")
  private String downloadUrl = null;

  @SerializedName("file_name")
  private String fileName = null;

  @SerializedName("file_size_bytes")
  private Long fileSizeBytes = null;

  public DownloadLinkResponse downloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * URL to download file.
   * @return downloadUrl
  **/
  @ApiModelProperty(example = "https://example.com/download", value = "URL to download file.")
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  public DownloadLinkResponse fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * File name of downloaded file.
   * @return fileName
  **/
  @ApiModelProperty(example = "file.pdf", value = "File name of downloaded file.")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public DownloadLinkResponse fileSizeBytes(Long fileSizeBytes) {
    this.fileSizeBytes = fileSizeBytes;
    return this;
  }

   /**
   * File size in bytes.
   * @return fileSizeBytes
  **/
  @ApiModelProperty(example = "1024", value = "File size in bytes.")
  public Long getFileSizeBytes() {
    return fileSizeBytes;
  }

  public void setFileSizeBytes(Long fileSizeBytes) {
    this.fileSizeBytes = fileSizeBytes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadLinkResponse downloadLinkResponse = (DownloadLinkResponse) o;
    return Objects.equals(this.downloadUrl, downloadLinkResponse.downloadUrl) &&
        Objects.equals(this.fileName, downloadLinkResponse.fileName) &&
        Objects.equals(this.fileSizeBytes, downloadLinkResponse.fileSizeBytes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadUrl, fileName, fileSizeBytes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadLinkResponse {\n");
    
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileSizeBytes: ").append(toIndentedString(fileSizeBytes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

