/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


package com.originstamp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Request object for a manual webhook request.
 */
@ApiModel(description = "Request object for a manual webhook request.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-18T14:06:09.411+01:00")
public class ManualWebhookRequest {
  @SerializedName("hash")
  private String hash = null;

  @SerializedName("webhook_url")
  private String webhookUrl = null;

  public ManualWebhookRequest hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * SHA-256 Hash in Hex representation.
   * @return hash
  **/
  @ApiModelProperty(example = "2c5d36be542f8f0e7345d77753a5d7ea61a443ba6a9a86bb060332ad56dba38e", required = true, value = "SHA-256 Hash in Hex representation.")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public ManualWebhookRequest webhookUrl(String webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

   /**
   * The target URL to which we send the timestamp information of the requested hash via a post request.
   * @return webhookUrl
  **/
  @ApiModelProperty(example = "http://localhost:80/originstamp/webhook", required = true, value = "The target URL to which we send the timestamp information of the requested hash via a post request.")
  public String getWebhookUrl() {
    return webhookUrl;
  }

  public void setWebhookUrl(String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManualWebhookRequest manualWebhookRequest = (ManualWebhookRequest) o;
    return Objects.equals(this.hash, manualWebhookRequest.hash) &&
        Objects.equals(this.webhookUrl, manualWebhookRequest.webhookUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, webhookUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManualWebhookRequest {\n");
    
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

