/*
 * OriginStamp Documentation
 * <br/>The following documentation describes the API v3 for OriginStamp. With this documentation you are able to try out the different requests and see the responses. For the authorization, add your API key to the Authorization header of your request.<br/><h2>Invoice</h2><p>The invoice is based on your individual usage. The following table illustrates the credits,that are billed in credits.</p><table><tr><th>Request Type</th><th>Condition</th><th>Credits</th><tr><th>Submission</th><th>create timestamp</th><th>1 Credit</th><tr><th>Submission</th><th>timestamp already exists</th><th>0.3 Credits</th><tr><th>Status</th><th>no timestamp information available</th><th>0.1 Credit</th><tr><th>Status</th><th>timestamp information</th><th>0.3 Credits</th><tr><th>Proof</th><th>no proof available</th><th>0.1 Credits</th><tr><th>Proof</th><th>merkle tree as proof</th><th>3 Credits</th><tr><th>Proof</th><th>seed as proof</th><th>3 Credits</th><tr><th>Proof</th><th>PDF Certificate</th><th>5 Credits</th><tr><th>Notification</th><th>webhook notification</th><th>1.5 Credits</th><tr><th>Notification</th><th>mail notification</th><th>5 Credits</th></table>
 *
 * OpenAPI spec version: 3.0
 * Contact: mail@originstamp.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TimestampData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * response object for the timestamp response.
 */
@ApiModel(description = "response object for the timestamp response.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-25T14:37:55.412Z")
public class TimestampResponse {
  @SerializedName("comment")
  private String comment = null;

  @SerializedName("created")
  private Boolean created = null;

  @SerializedName("date_created")
  private Long dateCreated = null;

  @SerializedName("hash_string")
  private String hashString = null;

  @SerializedName("timestamps")
  private List<TimestampData> timestamps = null;

  public TimestampResponse comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * The comment which was added in the submission of the hash.
   * @return comment
  **/
  @ApiModelProperty(value = "The comment which was added in the submission of the hash.")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public TimestampResponse created(Boolean created) {
    this.created = created;
    return this;
  }

   /**
   * Field is set to true if it is a novel hash. If the flag is false, the hash was already submitted before.
   * @return created
  **/
  @ApiModelProperty(example = "false", value = "Field is set to true if it is a novel hash. If the flag is false, the hash was already submitted before.")
  public Boolean isCreated() {
    return created;
  }

  public void setCreated(Boolean created) {
    this.created = created;
  }

  public TimestampResponse dateCreated(Long dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * The time when your hash was submitted to OriginStamp. This datetime is returned in [ms] since 1.1.1970 (unix epoch). The timezone is UTC. This is not considered as a true timestamp.
   * @return dateCreated
  **/
  @ApiModelProperty(value = "The time when your hash was submitted to OriginStamp. This datetime is returned in [ms] since 1.1.1970 (unix epoch). The timezone is UTC. This is not considered as a true timestamp.")
  public Long getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(Long dateCreated) {
    this.dateCreated = dateCreated;
  }

  public TimestampResponse hashString(String hashString) {
    this.hashString = hashString;
    return this;
  }

   /**
   * The submitted hash in hex representation.
   * @return hashString
  **/
  @ApiModelProperty(value = "The submitted hash in hex representation.")
  public String getHashString() {
    return hashString;
  }

  public void setHashString(String hashString) {
    this.hashString = hashString;
  }

  public TimestampResponse timestamps(List<TimestampData> timestamps) {
    this.timestamps = timestamps;
    return this;
  }

  public TimestampResponse addTimestampsItem(TimestampData timestampsItem) {
    if (this.timestamps == null) {
      this.timestamps = new ArrayList<TimestampData>();
    }
    this.timestamps.add(timestampsItem);
    return this;
  }

   /**
   * Contains all the timestamp data of your hash until now.
   * @return timestamps
  **/
  @ApiModelProperty(value = "Contains all the timestamp data of your hash until now.")
  public List<TimestampData> getTimestamps() {
    return timestamps;
  }

  public void setTimestamps(List<TimestampData> timestamps) {
    this.timestamps = timestamps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimestampResponse timestampResponse = (TimestampResponse) o;
    return Objects.equals(this.comment, timestampResponse.comment) &&
        Objects.equals(this.created, timestampResponse.created) &&
        Objects.equals(this.dateCreated, timestampResponse.dateCreated) &&
        Objects.equals(this.hashString, timestampResponse.hashString) &&
        Objects.equals(this.timestamps, timestampResponse.timestamps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, created, dateCreated, hashString, timestamps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimestampResponse {\n");
    
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    hashString: ").append(toIndentedString(hashString)).append("\n");
    sb.append("    timestamps: ").append(toIndentedString(timestamps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

